version: '3.7'

services:
  db:
    image: postgres:latest
    container_name: baza_systemy_chmurowe
    restart: always
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: postgre
      POSTGRES_PASSWORD: postgre
    volumes:
      - ./data/part_categories.csv:/data/part_categories.csv
      - ./data/parts.csv:/data/parts.csv
      - ./data/sets.csv:/data/sets.csv
      - ./data/themes.csv:/data/themes.csv
      - ./create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    ports:
      - "5432:5432"
